packages:
  - packages/*
  - examples/playground
  - examples/playground-room
  - examples/sfu-room-for-hosting
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
